### PR TITLE
week-2 HW

### PR DESCRIPTION
**Pull request by zabeth16**
Dear teacher ,   

My name is  陳思婷 , Discord name is  思 ZABETH .
Here is my week-2 HW , sorry for lately update.  
  
[http://15.168.25.179:3000/](url)  

Please review it , thank you ! 
Sincerely , Zabeth .

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Layout exceed screen width in small devices. There should not exist horizontal scroll bar in any situation.

**Comment by zabeth16** [comment]
Dear teacher, 
I revise the layout problem of horizontal scroll bar.
Please recheck it, thank you.

Sincerely, Zabeth .

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by zabeth16** [comment]
YYYEEAAAHHH

**Pull request merged**
