### PR TITLE
03 HW upload

### PR DESCRIPTION
**Pull request by zabeth16**
Dear teacher, 

My name is 陳思婷, Discord name is 思 ZABETH.
Here is my latest week-3 homework.  
I also add the link to home-page at attraction page logo.
Please review it, thank you.  

[http://15.168.25.179:3000/](url)

[http://15.168.25.179:3000/attraction/50](url)

Best wishes, Zabeth.

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Image slider should extend to full width and keep no margin space with navigator bar in the mobile version.

**Comment by zabeth16** [comment]
Dear teacher, 
I revise the  CSS format to compliant with the required format,  
sorry for careless about the mobile version.

Please recheck it, thank you !

**Review by cwpeng — CHANGES_REQUESTED** [review]
Layout in 360px width device exceed screen width slightly and title breaks into 2 lines.
15 168 25 179_3000_attraction_50(Samsung Galaxy S8+)

**Comment by zabeth16** [comment]
Dear teacher, 
I revise the latest version to compliant with the detail format which I ignore.
Please recheck it, thank you.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
