### PR TITLE
04 HW user auth

### PR DESCRIPTION
**Pull request by zabeth16**
Dear teacher,  
My name is 陳思婷, Discord name is 思 ZABETH.  
Here is my week 4 HW , please check it , thank you.  

[http://15.168.25.179:3000/](url)
[http://15.168.25.179:3000/attraction/46](url)

Sincerely, Zabeth.

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. I can sign in your system with wrong email password pair.
2. Password input should use input element with type password.

**Comment by zabeth16** [comment]
Dear teacher,   
I revise the input type and the logic of  login verification.
Please recheck it , thank you !

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by zabeth16** [comment]
Weeeeee

**Pull request merged**
